### ISSUE TITLE
Material design checklist

### ISSUE THREAD

**Issue by mkermani144** [mkermani144/wanna#191]
The app should meet material design rules below: (The list is updated frequently)

- [x] Mini drawer
- [x] Empty states
- [x] FAB position and sizing
- [x] List item heights
- [x] Settings page structure and texts
- [x] About page structure
- [x] Error messages
- [ ] Scrolling

**Comment by mkermani144** [comment]
The scrolling principles suggested by MD cannot be met at this time. It is reported as another issue in #207.

**Comment by mkermani144** [comment]
Closed by #206.
